# Site settings
title: Brandon Everett
description: 
url: 'http://brandoneverett.me'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Brandon Everett'
  email: brandon@brandoneverett.me
  twitter_username: bme2010
  facebook_username: brandon.everett.186
  github_username:  bmeverett
  linkedin_username:  brandon-everett-30746b59

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
